environment: prod
project_name: JEWEL
report_name: Jewel API regression
enter_point: https://apis.gemecosystem.com/gemEcosystemDashboard/v1/enter-point
jewel_user: jewel_automation_normal_user
jewel_bridge_token: 0f784394-542c-4ad4-b74a-503448e272141712469717255
glue_code: stepdefinitions
email_to: raja.arora@geminisolutions.com
email_report: n
tags: ' '
prod:
base_url: https://apis.gemecosystem.com
REQRESGETALL: https://reqres.in/api/users
REQRESPOST: https://reqres.in/api/users
REQRESPUT: https://reqres.in/api/users
REQRESDELETE: https://reqres.in/api/users